modLoader = "javafml"
loaderVersion = "[40,)"
license = "GNU GPLv3"
issueTrackerURL = "https://github.com/auioc/addrlimiter-mcmod/issues"

[[mods]]
    modId = "addrlimiter"
    version = "${file.jarVersion}"
    updateJSONURL = "https://hi.auioc.org/addrlimiter-mcmod/update/1.20.1.json"
    displayName = "AddrLimiter"
    displayURL = "http://hi.auioc.org/addrlimiter-mcmod/"
    credits = "AUIOC"
    authors = "WakelssSloth56"
    description = '''
'''

[[dependencies.addrlimiter]]
    modId = "forge"
    mandatory = true
    versionRange = "[47,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.addrlimiter]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.1,1.21)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.addrlimiter]]
    modId = "arnicalib"
    mandatory = true
    versionRange = "[6.0.2,)"
    ordering = "NONE"
    side = "BOTH"
