modLoader="javafml"
loaderVersion="[40,)"
license="GNU GPLv3"
issueTrackerURL="https://github.com/auioc/addrlimiter-mcmod/issues"

[[mods]]
modId="addrlimiter"
version="${file.jarVersion}"
updateJSONURL="https://hi.auioc.org/addrlimiter-mcmod/update/1.18.2.json"
displayName="AddrLimiter"
displayURL="http://hi.auioc.org/addrlimiter-mcmod/"
credits="AUIOC"
authors="WakelssSloth56"
description='''
'''

[[dependencies.addrlimiter]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.addrlimiter]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.addrlimiter]]
    modId="arnicalib"
    mandatory=true
    versionRange="[5.2.0,)"
    ordering="NONE"
    side="BOTH"
